apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-deployment
spec:
  selector:
    matchLabels:
      app: python-flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: pfd
        imagePullPolicy: Always
        image: kasad/pfd:latest
        resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
        ports:
          - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-svc
spec:
  ports:
  - port: 8000
    targetPort: 8008
    name: http
  selector:
    app: python-flask-app
