version: '3.7'

services:
        pfd:
                image: kasad/pfd:latest
                container_name: pfd
                ports:
                        - 8000:8008
                restart: always


        db:
                image: postgres:13
                container_name: postgres
                volumes:
                        - /home/asad/database-data:/var/lib/postgresql/data
                ports:
                        - 5433:5432
                restart: always
                environment:
                        POSTGRES_PASSWORD: Abcd@1234
                        POSTGRES_USER: postgres
