name: Docker build and push

on: [push]

#Env Variable
env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
        

jobs:
        build-docker-images:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Build the Docker image
                          run : docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/pfd:latest
                        
                        - name: docker login
                          run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

                        - name: Docker Push
                          run: docker push $DOCKERHUB_USERNAME/kasad/pdf:latest
        
