name: Docker Image CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches: 
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -
        name: Checkout 
        uses: actions/checkout@v2
    - 
        name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pfd:latest
